# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data,tables]
highlighter:      pygments

# Permalinks
permalink:        /posts/:title/

# Setup
title:            Harshali Singh
tagline:          '| thoughts.toString( )'
description:      'Musings of a female coder'
url:              http://harshalisingh.github.io
baseurl:          '/'
paginate:         5
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

#Author
author:
  name:           'Harshali Singh'
  url:            https://twitter.com/ItsHarshali

# Social Integration
social:
  twitter:        ItsHarshali
  disqus:         harshalisinghblog
  addthis_pubid:  ra-577bfc50e441a1f4

# Custom vars
version:          2.0.0

#Github
github:
  repo:           https://github.com/harshalisingh/harshalisingh.github.io

