# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Harshali Singh
tagline:          '| thoughts.toString()'
description:      'Musings of a female coder'
url:              http://harshalisingh.github.io

author:
  name:           'Harshali Singh'
  url:            https://twitter.com/ItsHarshali

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/harshalisingh/harshalisingh.github.io
